# Generated by Django 4.0 on 2022-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Post', verbose_name='関連記事'),
        ),
    ]
