# Generated by Django 4.0 on 2022-03-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='font',
            field=models.IntegerField(blank=True, choices=[(1, 'Noto Serif SC'), (2, 'EB Garamond'), (2, 'Shippori Mincho')], null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.category', unique=True, verbose_name='Category'),
        ),
    ]
