# Generated by Django 3.2.6 on 2022-07-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_draft_flg'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.CharField(default=0, max_length=100, verbose_name='説明'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='text',
            field=models.CharField(default=0, max_length=100, verbose_name='説明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_posts_post_relation_+', to='posts.Post', verbose_name='関連記事'),
        ),
    ]
